#ifndef __NOPMI_VOTE_H__
#define __NOPMI_VOTE_H__

#define PROFILE_CHG_VOTER		"PROFILE_CHG_VOTER"
#define MAIN_SET_VOTER			"MAIN_SET_VOTER"
#define BMS_FC_VOTER			"BMS_FC_VOTER"
#define DCP_CHG_VOTER			"DCP_CHG_VOTER"
#define PD_CHG_VOTER			"PD_CHG_VOTER"
#define STORE_MODE_VOTER		"STORE_MODE_VOTER"
#define AFC_CHG_DARK_VOTER		"AFC_CHG_DARK_VOTER"

#define PROFILE_CHG_VOTER		"PROFILE_CHG_VOTER"
#define MAIN_SET_VOTER			"MAIN_SET_VOTER"
#define BMS_FC_VOTER			"BMS_FC_VOTER"
#define DCP_CHG_VOTER			"DCP_CHG_VOTER"
#define PD_CHG_VOTER			"PD_CHG_VOTER"
#define STORE_MODE_VOTER		"STORE_MODE_VOTER"
#define AFC_CHG_DARK_VOTER		"AFC_CHG_DARK_VOTER"

//USB_ICL
#define DISABLE_AFC_VOTER       "DISABLE_AFC_VOTER"
#define OPS_SET_VOTER           "OPS_SET_VOTER"
#define CHARGER_TYPE_VOTER      "CHARGER_TYPE_VOTER"

//FCC
//#define CHARGER_TYPE_VOTER      "CHARGER_TYPE_VOTER"

#define JEITA_VOTER		"JEITA_VOTER"
#define JEITA_MIN_FCC   480

#endif
